alias la="ls -a"
alias ll="ls -l"

alias reboot="sudo reboot"
alias shutdown="sudo shutdown -h now"

alias docker-clean="docker system prune -a -f"
alias git-clean="git restore . && git clean -f"
alias apt-update="sudo apt-get update && sudo NEEDRESTART_MODE=a apt-get dist-upgrade -y"
alias apt-clean="sudo apt-get autoremove -y && sudo apt-get clean -y"
